version: "3.9"

services:
  db:
    build:
      context: ./database
    restart: always
    container_name: "postgres"
    ports:
      - "1234:5432"
    environment:
      POSTGRES_DB: volleyball_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    restart: always
    container_name: "dash_app"
    depends_on:
      - db
    ports:
      - "8050:8050"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: volleyball_app
    volumes:
      - ./app:/app

volumes:
  pg_data:
    driver: local
