version: "3.9"
services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "1234:5432"
    environment:
      POSTGRES_DB: volleyball_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dash_app
    depends_on:
      db:
        condition: service_started
    ports:
      - "8050:8050"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/volleyball_app
    working_dir: /app
    volumes:
      - .:/app

volumes:
  pg_data:
    driver: local
