version: "3.9"
services:
  db:
    build:
      context: .
    restart: always
    container_name: "postgres"
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: volleyball_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local

